### ISSUE TITLE
Bug: I started to receive 403 when using Indirectus

### ISSUE THREAD

**Issue by marekbrze** [linefusion/indirectus#11]
### Description of the bug

I started to receive 403 errors when trying to run Directus with an Admin Token (I checked the token multiple times).
`You don't have permission to access collection "directus_collections" or it does not exist. Queried in root.,`

I am using Directus 11.1.1

<img width="1520" alt="Screenshot 2024-11-03 at 20 43 04" src="https://github.com/user-attachments/assets/4e9d7532-b002-494f-aac2-7b365d2a26c2">

I really can't think about what is wrong. I used Directus before without any problems.

### Steps To Reproduce

1. Try to generate schema using Indirectus and Directus 11.1.1

**Comment by WoLfulus** [comment]
Did you upgrade Directus recently? Can you please confirm the authentication used and which URL path it's hitting? Note that you need admin permissions in this token in order for indirectus to read all the metadata from the server

**Comment by marekbrze** [comment]
Hi @WoLfulus,

I came back from the trip and I started to work on this once again. 

I triple checked the admin keys and the path that is hitting is "/collections".

I am almost 100% sure that it has to be connected to the new structure of the permissions in Directus.

**Comment by marekbrze** [comment]
I tinkered some more and after I changed http:// to https:// everything started working.... It's because I forced HTTPS on my server... Sorry for the trouble ...

**Comment by marekbrze** [comment]
I tinkered some more and after I changed http:// to https:// everything started working.... It's because I forced HTTPS on my server... Sorry for the trouble ...
