### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'one_collection')

### ISSUE THREAD

**Issue by nexthis** [linefusion/indirectus#3]
In https://github.com/linefusion/indirectus/blob/main/packages/cli/types/relationships.ts at line 117

when you have `field = public_favicon` and `collection = directus_settings` throw error `Cannot read properties of null (reading 'one_collection')`

to quick fix you need to add `if (relationship.collection === collection && relationship.field === field && relationship.field !== 'public_favicon')`

`directus:10.7.0`

**Comment by HarunKilic** [comment]
> In https://github.com/linefusion/indirectus/blob/main/packages/cli/types/relationships.ts at line 117
> 
> when you have `field = public_favicon` and `collection = directus_settings` throw error `Cannot read properties of null (reading 'one_collection')`
> 
> to quick fix you need to add `if (relationship.collection === collection && relationship.field === field && relationship.field !== 'public_favicon')`
> 
> `directus:10.7.0`

I've got same issue, did u manage to find a temporary solution?

**Comment by WoLfulus** [comment]
fixed in 0.2.2+

**Comment by HarunKilic** [comment]
Still having the issue :/
