### ISSUE TITLE
Bug: `--fetch` effect should be the default one?

### ISSUE THREAD

**Issue by rennokki** [linefusion/indirectus#6]
### Description of the bug

I find it confusing a bit that the cached schema is playing a role in the final `client.ts` generation.

I continuously tried to regen each time not knowing why it did not change, so I figured out I have to use the `--fetch` command.

I think the effect of the `--fetch` flag should be the default and possibly introduce a `--with-cache` flag to use the cache instead if needed?

**Comment by WoLfulus** [comment]
Makes sense, I'll push an update in a few hours.

**Comment by WoLfulus** [comment]
Hey! I couldn't do it, but I'm looking at it right now!

**Comment by WoLfulus** [comment]
I've finally changed how this behave. It should now always fetch from the server.
